version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
    volumes:
      - mediumclone_nestjs:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  mediumclone_nestjs:
